version: "3"

services:
  app:
    build: .
    env_file:
      - ./.env
    command: gunicorn -w 4 application.wsgi -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - .:/code
      - ./static:/code/static/
      - ./media:/code/media
    depends_on:
      - db
    networks:
      - web

  db:
    image: postgres:9.6-alpine
    hostname: db
    env_file:
      - ./.env
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - web

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./static:/code/static/
      - ./media:/code/media
    depends_on:
      - app
    ports:
      - "80:80"
    networks:
      - web

volumes:
  db-data:

networks:
  web:
    driver: bridge
